version: '3.8'

services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"  # Para desarrollo local

  backend:
    build: .
    container_name: fct_scraper_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - C:/Users/javie/AppData/Local/Instaloader:/root/.config/instaloader
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
