version: '3.8'

services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    networks:
      - fct_scraper_backend_fct_network  # Redis conectado a la red correcta

  backend:
    build: .
    container_name: fct_scraper_app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - C:/Users/javie/AppData/Local/Instaloader:/root/.config/instaloader
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - fct_scraper_backend_fct_network  # Backend conectado a la red correcta

  celery:
    build: .
    container_name: fct_scraper_celery
    command: celery -A tasks.celery_worker worker --loglevel=info -Q scraping
    volumes:
      - .:/app
      - C:/Users/javie/AppData/Local/Instaloader:/root/.config/instaloader
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - fct_scraper_backend_fct_network  # Celery conectado a la red correcta

networks:
  fct_scraper_backend_fct_network:
    driver: bridge  # Definimos la red correctamente
